spring:
  application:
    name: HelpDeskMCPServer
  main:
    web-application-type: none
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_ai
    username: nites
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
  console:
    stderr: true
