spring:
  application:
    name: HelpDeskMCPServer
  main:
    banner-mode: off
    log-startup-info: false
  profiles:
    default: local
  ai:
    mcp:
      server:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        table-name: policy_chunks
        dimensions: 1536
        initialize-schema: true
        remove-existing-vector-store-table: false
